export const MODELS = [
  {
    id: 'gemini-3.1-pro-preview',
    name: 'Pro Model',
    description: 'Best for complex reasoning, coding, and advanced tasks.',
    provider: 'google',
  },
  {
    id: 'gemini-3.1-pro-preview-thinking',
    name: 'Pro Model (Thinking)',
    description: 'Advanced reasoning with high thinking level.',
    provider: 'google',
  },
  {
    id: 'gemini-3-flash-preview',
    name: 'Flash Model',
    description: 'Fast and versatile for general tasks.',
    provider: 'google',
  },
  {
    id: 'gemini-3-flash-preview-search',
    name: 'Flash Model (Search)',
    description: 'Fast model with Google Search grounding.',
    provider: 'google',
  },
  {
    id: 'gemini-3.1-flash-lite-preview',
    name: 'Flash Lite Model',
    description: 'Lowest latency for quick responses.',
    provider: 'google',
  },
  {
    id: 'gemini-3.1-flash-image-preview',
    name: 'Image Generation Model',
    description: 'Generate high-quality images from text.',
    provider: 'google',
  },
  {
    id: 'veo-3.1-fast-generate-preview',
    name: 'Veo 3.1 Video Generation',
    description: 'Generate videos from text prompts.',
    provider: 'google',
  },
  {
    id: 'lyria-3-clip-preview',
    name: 'Lyria 3 Music Generation',
    description: 'Generate short music clips from text.',
    provider: 'google',
  },
  {
    id: 'gemini-2.5-flash-preview-tts',
    name: 'Text-to-Speech Model',
    description: 'Generate speech from text.',
    provider: 'google',
  },
  {
    id: 'gpt-4o',
    name: 'GPT-4o',
    description: 'OpenAI flagship model for complex tasks.',
    provider: 'openai',
  },
  {
    id: 'gpt-4o-mini',
    name: 'GPT-4o Mini',
    description: 'Fast and cost-effective OpenAI model.',
    provider: 'openai',
  },
  {
    id: 'claude-3-5-sonnet-latest',
    name: 'Claude 3.5 Sonnet',
    description: 'Anthropic flagship model for coding and reasoning.',
    provider: 'anthropic',
  },
  {
    id: 'claude-3-5-haiku-latest',
    name: 'Claude 3.5 Haiku',
    description: 'Fast and efficient Anthropic model.',
    provider: 'anthropic',
  },
];
